export default {
  authors: [],
  courses: [],
  navbar_items: [],
  blogs: [],
  schedules: [],
  costs: [],
  classTypes: [],
  dietConsultations: [],
  massageTypes: [],
  testimonials: [],
  eventTypes: [],
  upload: [],
  authToken: {
    user: null,
    token: null,
  },
  requesting: false,
  successful: false,
  messages: [],
  errors: [],
}
