# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='buisness_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='listings.List'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='story_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
